# Generated by Django 3.1 on 2021-03-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='listings',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Listing'),
        ),
    ]
