# Generated by Django 3.1 on 2021-04-07 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210329_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
