# Generated by Django 3.1 on 2020-10-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='initial_Price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
