# Generated by Django 3.1 on 2020-10-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_initial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user_listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='auctions.user'),
            preserve_default=False,
        ),
    ]
