# Generated by Django 3.1 on 2020-10-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201001_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='velue',
            new_name='value',
        ),
    ]
