# Generated by Django 3.1 on 2020-10-07 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201001_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_list_users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
